TARGET = STARTKIT
APP_NAME = app_nbsp_startkit_demo
USED_MODULES = module_nbsp

SOURCE_DIRS = src/*
INCLUDE_DIRS = src/*
XCC_FLAGS = -g -Wall -O3
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
