TARGET = XS1-L16A-128-QF124-C10
APP_NAME = app_nbsp_simple_example
USED_MODULES = module_nbsp

SOURCE_DIRS = src/*
INCLUDE_DIRS = src/*
XCC_FLAGS = -g -Wall -O3
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
